{
  "formatVersion": "1.1",
  "component": {
    "group": "com.microservices.core",
    "module": "microservice-util",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "microservice-util-1.0-SNAPSHOT.jar",
          "url": "microservice-util-1.0-SNAPSHOT.jar",
          "size": 7893,
          "sha512": "a1c03d7e7267e271684bf024d1d425b347260c515895198eedd1951ca49e192b0b7d639dd74a092cf582771eb94777555e549de13c2ddd513fd044f9b5aacf7e",
          "sha256": "6a93269e0aacb112b286431f74dd634e046647631283528a0b3d4e2005f25227",
          "sha1": "f13fbd20ea09d4e413705b8f156ab82717e9e132",
          "md5": "5ebb5ca01b9e65c31cbb609e99fe4b2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "3.5.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux"
        }
      ],
      "files": [
        {
          "name": "microservice-util-1.0-SNAPSHOT.jar",
          "url": "microservice-util-1.0-SNAPSHOT.jar",
          "size": 7893,
          "sha512": "a1c03d7e7267e271684bf024d1d425b347260c515895198eedd1951ca49e192b0b7d639dd74a092cf582771eb94777555e549de13c2ddd513fd044f9b5aacf7e",
          "sha256": "6a93269e0aacb112b286431f74dd634e046647631283528a0b3d4e2005f25227",
          "sha1": "f13fbd20ea09d4e413705b8f156ab82717e9e132",
          "md5": "5ebb5ca01b9e65c31cbb609e99fe4b2d"
        }
      ]
    }
  ]
}
