{
  "formatVersion": "1.1",
  "component": {
    "group": "com.microservices.core",
    "module": "microservice-util",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "microservice-util-1.0.0.jar",
          "url": "microservice-util-1.0.0.jar",
          "size": 16400,
          "sha512": "aa3bdc216f14da0d71b11ba615640573088a75c911e8bfe87bf7430ff5c702fe4406dac8b21af76c0ab04f531927d34fbb3b3f554b2e2a3cf94918334d5f5700",
          "sha256": "c2c1b44fb2e6f484b903ba327e6d6d86143be625da0fd930b28aacf22cc19422",
          "sha1": "1422da7a275a1be91411e63cb0ddd5a06fb87cd3",
          "md5": "7e094e3dec5701cbc06a80aa3cc5d6be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "3.5.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator"
        }
      ],
      "files": [
        {
          "name": "microservice-util-1.0.0.jar",
          "url": "microservice-util-1.0.0.jar",
          "size": 16400,
          "sha512": "aa3bdc216f14da0d71b11ba615640573088a75c911e8bfe87bf7430ff5c702fe4406dac8b21af76c0ab04f531927d34fbb3b3f554b2e2a3cf94918334d5f5700",
          "sha256": "c2c1b44fb2e6f484b903ba327e6d6d86143be625da0fd930b28aacf22cc19422",
          "sha1": "1422da7a275a1be91411e63cb0ddd5a06fb87cd3",
          "md5": "7e094e3dec5701cbc06a80aa3cc5d6be"
        }
      ]
    }
  ]
}
