{
  "formatVersion": "1.1",
  "component": {
    "group": "com.microservices.core",
    "module": "microservice-util",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "microservice-util-1.0.0.jar",
          "url": "microservice-util-1.0.0.jar",
          "size": 10360,
          "sha512": "e44b830cf8770b3535c8d11b5c4d94b19adaf8d955c65f2fbe740f27483a04231e7f41ba96ed29709aa5dc15f2167ce006a70804694eca52316d84e082e6a702",
          "sha256": "b161eb43841feebe50912cc2a5def29974599e2294f9a16323182cbe59473cd9",
          "sha1": "17cc8c18bb946a4188aa33ffbea1f25dd232955e",
          "md5": "7113e532446308633cba35bec898048a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "3.5.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux"
        }
      ],
      "files": [
        {
          "name": "microservice-util-1.0.0.jar",
          "url": "microservice-util-1.0.0.jar",
          "size": 10360,
          "sha512": "e44b830cf8770b3535c8d11b5c4d94b19adaf8d955c65f2fbe740f27483a04231e7f41ba96ed29709aa5dc15f2167ce006a70804694eca52316d84e082e6a702",
          "sha256": "b161eb43841feebe50912cc2a5def29974599e2294f9a16323182cbe59473cd9",
          "sha1": "17cc8c18bb946a4188aa33ffbea1f25dd232955e",
          "md5": "7113e532446308633cba35bec898048a"
        }
      ]
    }
  ]
}
